# Generated by Django 5.0.1 on 2024-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
